export { HomePage } from './home-page'
export { homePageMetadata } from './home.seo'

export { Hero, heroData } from './sections/hero'
export type { HeroData } from './sections/hero'
export { Partners, partnersData } from './sections/partners'
export type { PartnersData, PartnerCompany, PartnerHighlight } from './sections/partners'
export { Metrics, metricsData } from './sections/metrics'
export type { MetricsData, Metric } from './sections/metrics'
export { Features, featuresData } from './sections/features'
export type { Feature, FeaturesData } from './sections/features'
export { CaseStudiesPreview, caseStudiesPreviewData } from './sections/case-studies-preview'
export type { CaseStudiesPreviewData, CaseStudyPreview } from './sections/case-studies-preview'
export { Process, processData } from './sections/process'
export type { ProcessData, ProcessStep } from './sections/process'
export { Industries, industriesData } from './sections/industries'
export type { IndustriesData, Industry } from './sections/industries'
export { PricingPreview, pricingPreviewData } from './sections/pricing-preview'
export type { PricingPreviewData } from './sections/pricing-preview'
export { Support, supportData } from './sections/support'
export type { SupportData, SupportHighlight } from './sections/support'
export { Testimonials, testimonialsData } from './sections/testimonials'
export type { Testimonial, TestimonialsData } from './sections/testimonials'
export { Faq, faqData } from './sections/faq'
export type { FaqItem, FaqData } from './sections/faq'
export { Cta, ctaData } from './sections/cta'
export type { CtaData } from './sections/cta'
