/**
 * Supabase Database Types
 *
 * Generated: 2025-11-07 23:48:18 UTC
 * Schemas: public
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run `python scripts/generate-supabase-types.py` to regenerate.
 *
 * Best Practices:
 * 1. Never manually edit this file
 * 2. Regenerate after any database schema changes
 * 3. Use type helpers for complex queries:
 *    - Tables<'tableName'> for row types
 *    - TablesInsert<'tableName'> for inserts
 *    - TablesUpdate<'tableName'> for updates
 * 4. Create wrapper types in separate files for business logic
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5";
  };
  public: {
    Tables: {
      account_lockouts: {
        Row: {
          created_at: string | null;
          email: string;
          id: string;
          locked_by: string | null;
          locked_until: string;
          reason: string | null;
        };
        Insert: {
          created_at?: string | null;
          email: string;
          id?: string;
          locked_by?: string | null;
          locked_until: string;
          reason?: string | null;
        };
        Update: {
          created_at?: string | null;
          email?: string;
          id?: string;
          locked_by?: string | null;
          locked_until?: string;
          reason?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          action: string;
          actor_profile_id: string | null;
          change_summary: Json;
          created_at: string;
          id: number;
          ip_address: unknown;
          profile_id: string | null;
          resource_id: string | null;
          resource_table: string;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table: string;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table?: string;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_fk";
            columns: ["actor_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_log_actor_fk";
            columns: ["actor_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_log_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_log_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_log_2025q4: {
        Row: {
          action: string;
          actor_profile_id: string | null;
          change_summary: Json;
          created_at: string;
          id: number;
          ip_address: unknown;
          profile_id: string | null;
          resource_id: string | null;
          resource_table: string;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table: string;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table?: string;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      audit_log_archive: {
        Row: {
          action: string;
          actor_profile_id: string | null;
          archived_at: string;
          change_summary: Json;
          created_at: string;
          id: number;
          ip_address: unknown;
          profile_id: string | null;
          resource_id: string | null;
          resource_table: string;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_profile_id?: string | null;
          archived_at?: string;
          change_summary?: Json;
          created_at: string;
          id: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table: string;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_profile_id?: string | null;
          archived_at?: string;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table?: string;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      audit_log_before_2025q4: {
        Row: {
          action: string;
          actor_profile_id: string | null;
          change_summary: Json;
          created_at: string;
          id: number;
          ip_address: unknown;
          profile_id: string | null;
          resource_id: string | null;
          resource_table: string;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table: string;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table?: string;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      audit_log_future: {
        Row: {
          action: string;
          actor_profile_id: string | null;
          change_summary: Json;
          created_at: string;
          id: number;
          ip_address: unknown;
          profile_id: string | null;
          resource_id: string | null;
          resource_table: string;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table: string;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_profile_id?: string | null;
          change_summary?: Json;
          created_at?: string;
          id?: number;
          ip_address?: unknown;
          profile_id?: string | null;
          resource_id?: string | null;
          resource_table?: string;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      backup_catalog: {
        Row: {
          backup_type: string;
          completed_at: string | null;
          id: string;
          location: string;
          notes: string | null;
          size_bytes: number | null;
          started_at: string;
          status: string;
        };
        Insert: {
          backup_type: string;
          completed_at?: string | null;
          id?: string;
          location: string;
          notes?: string | null;
          size_bytes?: number | null;
          started_at?: string;
          status?: string;
        };
        Update: {
          backup_type?: string;
          completed_at?: string | null;
          id?: string;
          location?: string;
          notes?: string | null;
          size_bytes?: number | null;
          started_at?: string;
          status?: string;
        };
        Relationships: [];
      };
      billing_alert: {
        Row: {
          acknowledged_at: string | null;
          acknowledged_by: string | null;
          action_required: boolean | null;
          action_url: string | null;
          alert_type: string;
          auto_resolve_at: string | null;
          created_at: string;
          id: string;
          invoice_id: string | null;
          message: string;
          metadata: Json | null;
          payment_intent_id: string | null;
          profile_id: string;
          resolved_at: string | null;
          severity: string;
          status: string | null;
          subscription_id: string | null;
          title: string;
          updated_at: string;
        };
        Insert: {
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          action_required?: boolean | null;
          action_url?: string | null;
          alert_type: string;
          auto_resolve_at?: string | null;
          created_at?: string;
          id?: string;
          invoice_id?: string | null;
          message: string;
          metadata?: Json | null;
          payment_intent_id?: string | null;
          profile_id: string;
          resolved_at?: string | null;
          severity: string;
          status?: string | null;
          subscription_id?: string | null;
          title: string;
          updated_at?: string;
        };
        Update: {
          acknowledged_at?: string | null;
          acknowledged_by?: string | null;
          action_required?: boolean | null;
          action_url?: string | null;
          alert_type?: string;
          auto_resolve_at?: string | null;
          created_at?: string;
          id?: string;
          invoice_id?: string | null;
          message?: string;
          metadata?: Json | null;
          payment_intent_id?: string | null;
          profile_id?: string;
          resolved_at?: string | null;
          severity?: string;
          status?: string | null;
          subscription_id?: string | null;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "billing_alert_acknowledged_by_fkey";
            columns: ["acknowledged_by"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_acknowledged_by_fkey";
            columns: ["acknowledged_by"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoice";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_payment_intent_id_fkey";
            columns: ["payment_intent_id"];
            isOneToOne: false;
            referencedRelation: "payment_intent";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "billing_alert_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
        ];
      };
      charge: {
        Row: {
          amount: number;
          amount_captured: number;
          amount_refunded: number;
          application_fee_amount: number | null;
          captured: boolean | null;
          card_brand: string | null;
          card_exp_month: number | null;
          card_exp_year: number | null;
          card_last4: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          dispute_id: string | null;
          disputed: boolean | null;
          failure_balance_transaction: string | null;
          failure_code: string | null;
          failure_message: string | null;
          fee: number | null;
          fee_details: Json | null;
          id: string;
          invoice_id: string | null;
          metadata: Json | null;
          net: number | null;
          paid: boolean;
          payment_intent_id: string | null;
          payment_method_type: string | null;
          profile_id: string;
          receipt_number: string | null;
          receipt_url: string | null;
          refunded: boolean;
          statement_descriptor: string | null;
          status: string;
          stripe_balance_transaction_id: string | null;
          stripe_charge_id: string;
          stripe_payment_method_id: string | null;
          transfer_id: string | null;
          updated_at: string;
        };
        Insert: {
          amount: number;
          amount_captured: number;
          amount_refunded?: number;
          application_fee_amount?: number | null;
          captured?: boolean | null;
          card_brand?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          card_last4?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          dispute_id?: string | null;
          disputed?: boolean | null;
          failure_balance_transaction?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          fee?: number | null;
          fee_details?: Json | null;
          id?: string;
          invoice_id?: string | null;
          metadata?: Json | null;
          net?: number | null;
          paid?: boolean;
          payment_intent_id?: string | null;
          payment_method_type?: string | null;
          profile_id: string;
          receipt_number?: string | null;
          receipt_url?: string | null;
          refunded?: boolean;
          statement_descriptor?: string | null;
          status: string;
          stripe_balance_transaction_id?: string | null;
          stripe_charge_id: string;
          stripe_payment_method_id?: string | null;
          transfer_id?: string | null;
          updated_at?: string;
        };
        Update: {
          amount?: number;
          amount_captured?: number;
          amount_refunded?: number;
          application_fee_amount?: number | null;
          captured?: boolean | null;
          card_brand?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          card_last4?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          dispute_id?: string | null;
          disputed?: boolean | null;
          failure_balance_transaction?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          fee?: number | null;
          fee_details?: Json | null;
          id?: string;
          invoice_id?: string | null;
          metadata?: Json | null;
          net?: number | null;
          paid?: boolean;
          payment_intent_id?: string | null;
          payment_method_type?: string | null;
          profile_id?: string;
          receipt_number?: string | null;
          receipt_url?: string | null;
          refunded?: boolean;
          statement_descriptor?: string | null;
          status?: string;
          stripe_balance_transaction_id?: string | null;
          stripe_charge_id?: string;
          stripe_payment_method_id?: string | null;
          transfer_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "charge_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoice";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "charge_payment_intent_id_fkey";
            columns: ["payment_intent_id"];
            isOneToOne: false;
            referencedRelation: "payment_intent";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "charge_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "charge_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      client_site: {
        Row: {
          created_at: string;
          custom_domain: string | null;
          deleted_at: string | null;
          deployed_at: string | null;
          deployment_notes: string | null;
          deployment_url: string | null;
          design_brief: Json;
          id: string;
          last_revision_at: string | null;
          plan_id: string | null;
          profile_id: string;
          site_name: string;
          slug: string | null;
          status: Database["public"]["Enums"]["site_status"];
          subscription_id: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          custom_domain?: string | null;
          deleted_at?: string | null;
          deployed_at?: string | null;
          deployment_notes?: string | null;
          deployment_url?: string | null;
          design_brief?: Json;
          id?: string;
          last_revision_at?: string | null;
          plan_id?: string | null;
          profile_id: string;
          site_name: string;
          slug?: string | null;
          status?: Database["public"]["Enums"]["site_status"];
          subscription_id?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          custom_domain?: string | null;
          deleted_at?: string | null;
          deployed_at?: string | null;
          deployment_notes?: string | null;
          deployment_url?: string | null;
          design_brief?: Json;
          id?: string;
          last_revision_at?: string | null;
          plan_id?: string | null;
          profile_id?: string;
          site_name?: string;
          slug?: string | null;
          status?: Database["public"]["Enums"]["site_status"];
          subscription_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "client_site_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "analytics_mrr";
            referencedColumns: ["plan_id"];
          },
          {
            foreignKeyName: "client_site_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plan";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_site_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plan_pricing";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_site_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_site_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "client_site_subscription_fk";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
        ];
      };
      contact_submission: {
        Row: {
          assigned_to: string | null;
          company_name: string | null;
          consent_ip_address: unknown;
          consent_timestamp: string | null;
          contacted_at: string | null;
          converted_at: string | null;
          created_at: string | null;
          deleted_at: string | null;
          email: string;
          full_name: string;
          id: string;
          landing_page: string | null;
          lead_score: number | null;
          marketing_opt_in: boolean | null;
          message: string;
          phone: string | null;
          referrer_url: string | null;
          service_interest: string;
          status: string | null;
          updated_at: string | null;
          utm_campaign: string | null;
          utm_content: string | null;
          utm_medium: string | null;
          utm_source: string | null;
          utm_term: string | null;
        };
        Insert: {
          assigned_to?: string | null;
          company_name?: string | null;
          consent_ip_address?: unknown;
          consent_timestamp?: string | null;
          contacted_at?: string | null;
          converted_at?: string | null;
          created_at?: string | null;
          deleted_at?: string | null;
          email: string;
          full_name: string;
          id?: string;
          landing_page?: string | null;
          lead_score?: number | null;
          marketing_opt_in?: boolean | null;
          message: string;
          phone?: string | null;
          referrer_url?: string | null;
          service_interest: string;
          status?: string | null;
          updated_at?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_medium?: string | null;
          utm_source?: string | null;
          utm_term?: string | null;
        };
        Update: {
          assigned_to?: string | null;
          company_name?: string | null;
          consent_ip_address?: unknown;
          consent_timestamp?: string | null;
          contacted_at?: string | null;
          converted_at?: string | null;
          created_at?: string | null;
          deleted_at?: string | null;
          email?: string;
          full_name?: string;
          id?: string;
          landing_page?: string | null;
          lead_score?: number | null;
          marketing_opt_in?: boolean | null;
          message?: string;
          phone?: string | null;
          referrer_url?: string | null;
          service_interest?: string;
          status?: string | null;
          updated_at?: string | null;
          utm_campaign?: string | null;
          utm_content?: string | null;
          utm_medium?: string | null;
          utm_source?: string | null;
          utm_term?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "contact_submission_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "contact_submission_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      data_retention_policy: {
        Row: {
          auto_purge: boolean;
          created_at: string;
          last_enforced_at: string | null;
          notes: string | null;
          retention_period: unknown;
          table_name: string;
          updated_at: string;
        };
        Insert: {
          auto_purge?: boolean;
          created_at?: string;
          last_enforced_at?: string | null;
          notes?: string | null;
          retention_period: unknown;
          table_name: string;
          updated_at?: string;
        };
        Update: {
          auto_purge?: boolean;
          created_at?: string;
          last_enforced_at?: string | null;
          notes?: string | null;
          retention_period?: unknown;
          table_name?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoice: {
        Row: {
          amount_due: number;
          amount_paid: number;
          amount_remaining: number;
          attempt_count: number | null;
          collection_method: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          discount_amount: number | null;
          due_date: string | null;
          hosted_invoice_url: string | null;
          id: string;
          invoice_number: string | null;
          invoice_pdf_url: string | null;
          metadata: Json | null;
          next_payment_attempt: string | null;
          paid_at: string | null;
          period_end: string | null;
          period_start: string | null;
          profile_id: string;
          statement_descriptor: string | null;
          status: string;
          stripe_invoice_id: string;
          stripe_payment_intent_id: string | null;
          subscription_id: string | null;
          subtotal: number;
          tax: number | null;
          total: number;
          updated_at: string;
          voided_at: string | null;
        };
        Insert: {
          amount_due: number;
          amount_paid?: number;
          amount_remaining: number;
          attempt_count?: number | null;
          collection_method?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          discount_amount?: number | null;
          due_date?: string | null;
          hosted_invoice_url?: string | null;
          id?: string;
          invoice_number?: string | null;
          invoice_pdf_url?: string | null;
          metadata?: Json | null;
          next_payment_attempt?: string | null;
          paid_at?: string | null;
          period_end?: string | null;
          period_start?: string | null;
          profile_id: string;
          statement_descriptor?: string | null;
          status: string;
          stripe_invoice_id: string;
          stripe_payment_intent_id?: string | null;
          subscription_id?: string | null;
          subtotal: number;
          tax?: number | null;
          total: number;
          updated_at?: string;
          voided_at?: string | null;
        };
        Update: {
          amount_due?: number;
          amount_paid?: number;
          amount_remaining?: number;
          attempt_count?: number | null;
          collection_method?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          discount_amount?: number | null;
          due_date?: string | null;
          hosted_invoice_url?: string | null;
          id?: string;
          invoice_number?: string | null;
          invoice_pdf_url?: string | null;
          metadata?: Json | null;
          next_payment_attempt?: string | null;
          paid_at?: string | null;
          period_end?: string | null;
          period_start?: string | null;
          profile_id?: string;
          statement_descriptor?: string | null;
          status?: string;
          stripe_invoice_id?: string;
          stripe_payment_intent_id?: string | null;
          subscription_id?: string | null;
          subtotal?: number;
          tax?: number | null;
          total?: number;
          updated_at?: string;
          voided_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "invoice_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invoice_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
        ];
      };
      login_attempts: {
        Row: {
          city: string | null;
          country_code: string | null;
          created_at: string | null;
          device_fingerprint: string | null;
          email: string;
          failure_reason: string | null;
          id: string;
          ip_address: unknown;
          success: boolean;
          user_agent: string | null;
        };
        Insert: {
          city?: string | null;
          country_code?: string | null;
          created_at?: string | null;
          device_fingerprint?: string | null;
          email: string;
          failure_reason?: string | null;
          id?: string;
          ip_address?: unknown;
          success: boolean;
          user_agent?: string | null;
        };
        Update: {
          city?: string | null;
          country_code?: string | null;
          created_at?: string | null;
          device_fingerprint?: string | null;
          email?: string;
          failure_reason?: string | null;
          id?: string;
          ip_address?: unknown;
          success?: boolean;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      notification: {
        Row: {
          action_url: string | null;
          body: string | null;
          created_at: string;
          expires_at: string | null;
          id: string;
          metadata: Json;
          notification_type: Database["public"]["Enums"]["notification_type"];
          profile_id: string;
          read_at: string | null;
          title: string;
          updated_at: string;
        };
        Insert: {
          action_url?: string | null;
          body?: string | null;
          created_at?: string;
          expires_at?: string | null;
          id?: string;
          metadata?: Json;
          notification_type: Database["public"]["Enums"]["notification_type"];
          profile_id: string;
          read_at?: string | null;
          title: string;
          updated_at?: string;
        };
        Update: {
          action_url?: string | null;
          body?: string | null;
          created_at?: string;
          expires_at?: string | null;
          id?: string;
          metadata?: Json;
          notification_type?: Database["public"]["Enums"]["notification_type"];
          profile_id?: string;
          read_at?: string | null;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_history: {
        Row: {
          action_url: string | null;
          archived_at: string;
          body: string | null;
          created_at: string;
          expires_at: string | null;
          id: string;
          metadata: Json;
          notification_type: Database["public"]["Enums"]["notification_type"];
          profile_id: string;
          read_at: string | null;
          title: string;
        };
        Insert: {
          action_url?: string | null;
          archived_at?: string;
          body?: string | null;
          created_at: string;
          expires_at?: string | null;
          id: string;
          metadata?: Json;
          notification_type: Database["public"]["Enums"]["notification_type"];
          profile_id: string;
          read_at?: string | null;
          title: string;
        };
        Update: {
          action_url?: string | null;
          archived_at?: string;
          body?: string | null;
          created_at?: string;
          expires_at?: string | null;
          id?: string;
          metadata?: Json;
          notification_type?: Database["public"]["Enums"]["notification_type"];
          profile_id?: string;
          read_at?: string | null;
          title?: string;
        };
        Relationships: [];
      };
      otp_attempt_log: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          ip_address: unknown;
          success: boolean;
          verification_type: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: string;
          ip_address?: unknown;
          success: boolean;
          verification_type: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          ip_address?: unknown;
          success?: boolean;
          verification_type?: string;
        };
        Relationships: [];
      };
      otp_verification: {
        Row: {
          attempts: number | null;
          created_at: string | null;
          email: string;
          expires_at: string;
          id: string;
          otp_code: string;
          otp_hash: string;
          otp_salt: string;
          profile_id: string | null;
          updated_at: string | null;
          verification_type: string;
          verified_at: string | null;
        };
        Insert: {
          attempts?: number | null;
          created_at?: string | null;
          email: string;
          expires_at: string;
          id?: string;
          otp_code: string;
          otp_hash: string;
          otp_salt: string;
          profile_id?: string | null;
          updated_at?: string | null;
          verification_type: string;
          verified_at?: string | null;
        };
        Update: {
          attempts?: number | null;
          created_at?: string | null;
          email?: string;
          expires_at?: string;
          id?: string;
          otp_code?: string;
          otp_hash?: string;
          otp_salt?: string;
          profile_id?: string | null;
          updated_at?: string | null;
          verification_type?: string;
          verified_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "otp_verification_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "otp_verification_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      payment_intent: {
        Row: {
          amount: number;
          amount_capturable: number | null;
          amount_received: number | null;
          canceled_at: string | null;
          cancellation_reason: string | null;
          capture_method: string | null;
          confirmation_method: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          id: string;
          invoice_id: string | null;
          last_payment_error: Json | null;
          metadata: Json | null;
          payment_method_types: string[] | null;
          profile_id: string;
          receipt_email: string | null;
          statement_descriptor: string | null;
          status: string;
          stripe_payment_intent_id: string;
          stripe_payment_method_id: string | null;
          subscription_id: string | null;
          updated_at: string;
        };
        Insert: {
          amount: number;
          amount_capturable?: number | null;
          amount_received?: number | null;
          canceled_at?: string | null;
          cancellation_reason?: string | null;
          capture_method?: string | null;
          confirmation_method?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          invoice_id?: string | null;
          last_payment_error?: Json | null;
          metadata?: Json | null;
          payment_method_types?: string[] | null;
          profile_id: string;
          receipt_email?: string | null;
          statement_descriptor?: string | null;
          status: string;
          stripe_payment_intent_id: string;
          stripe_payment_method_id?: string | null;
          subscription_id?: string | null;
          updated_at?: string;
        };
        Update: {
          amount?: number;
          amount_capturable?: number | null;
          amount_received?: number | null;
          canceled_at?: string | null;
          cancellation_reason?: string | null;
          capture_method?: string | null;
          confirmation_method?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          invoice_id?: string | null;
          last_payment_error?: Json | null;
          metadata?: Json | null;
          payment_method_types?: string[] | null;
          profile_id?: string;
          receipt_email?: string | null;
          statement_descriptor?: string | null;
          status?: string;
          stripe_payment_intent_id?: string;
          stripe_payment_method_id?: string | null;
          subscription_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payment_intent_invoice_id_fkey";
            columns: ["invoice_id"];
            isOneToOne: false;
            referencedRelation: "invoice";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_intent_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_intent_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_intent_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
        ];
      };
      payment_method: {
        Row: {
          billing_address_line1: string | null;
          billing_address_line2: string | null;
          billing_city: string | null;
          billing_country: string | null;
          billing_email: string | null;
          billing_name: string | null;
          billing_phone: string | null;
          billing_postal_code: string | null;
          billing_state: string | null;
          card_brand: string | null;
          card_country: string | null;
          card_exp_month: number | null;
          card_exp_year: number | null;
          card_fingerprint: string | null;
          card_funding: string | null;
          card_last4: string | null;
          created_at: string;
          deleted_at: string | null;
          id: string;
          is_default: boolean | null;
          metadata: Json | null;
          profile_id: string;
          status: string | null;
          stripe_payment_method_id: string;
          type: string;
          updated_at: string;
        };
        Insert: {
          billing_address_line1?: string | null;
          billing_address_line2?: string | null;
          billing_city?: string | null;
          billing_country?: string | null;
          billing_email?: string | null;
          billing_name?: string | null;
          billing_phone?: string | null;
          billing_postal_code?: string | null;
          billing_state?: string | null;
          card_brand?: string | null;
          card_country?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          card_fingerprint?: string | null;
          card_funding?: string | null;
          card_last4?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_default?: boolean | null;
          metadata?: Json | null;
          profile_id: string;
          status?: string | null;
          stripe_payment_method_id: string;
          type: string;
          updated_at?: string;
        };
        Update: {
          billing_address_line1?: string | null;
          billing_address_line2?: string | null;
          billing_city?: string | null;
          billing_country?: string | null;
          billing_email?: string | null;
          billing_name?: string | null;
          billing_phone?: string | null;
          billing_postal_code?: string | null;
          billing_state?: string | null;
          card_brand?: string | null;
          card_country?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          card_fingerprint?: string | null;
          card_funding?: string | null;
          card_last4?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          id?: string;
          is_default?: boolean | null;
          metadata?: Json | null;
          profile_id?: string;
          status?: string | null;
          stripe_payment_method_id?: string;
          type?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "payment_method_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "payment_method_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      plan: {
        Row: {
          created_at: string;
          currency_code: string;
          description: string | null;
          features: Json;
          id: string;
          is_active: boolean;
          name: string;
          page_limit: number | null;
          price_monthly_cents: number | null;
          price_yearly_cents: number | null;
          revision_limit: number | null;
          setup_fee_cents: number | null;
          slug: string;
          sort_order: number;
          stripe_price_id_monthly: string | null;
          stripe_price_id_yearly: string | null;
          stripe_product_id: string | null;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          currency_code?: string;
          description?: string | null;
          features?: Json;
          id?: string;
          is_active?: boolean;
          name: string;
          page_limit?: number | null;
          price_monthly_cents?: number | null;
          price_yearly_cents?: number | null;
          revision_limit?: number | null;
          setup_fee_cents?: number | null;
          slug: string;
          sort_order?: number;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_yearly?: string | null;
          stripe_product_id?: string | null;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          currency_code?: string;
          description?: string | null;
          features?: Json;
          id?: string;
          is_active?: boolean;
          name?: string;
          page_limit?: number | null;
          price_monthly_cents?: number | null;
          price_yearly_cents?: number | null;
          revision_limit?: number | null;
          setup_fee_cents?: number | null;
          slug?: string;
          sort_order?: number;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_yearly?: string | null;
          stripe_product_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      profile: {
        Row: {
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          company_name: string | null;
          company_website: string | null;
          contact_email: string | null;
          contact_name: string | null;
          contact_phone: string | null;
          country: string | null;
          created_at: string;
          deleted_at: string | null;
          email_verified: boolean | null;
          id: string;
          marketing_opt_in: boolean;
          onboarding_notes: string | null;
          postal_code: string | null;
          region: string | null;
          role: Database["public"]["Enums"]["user_role"];
          stripe_customer_id: string | null;
          updated_at: string;
        };
        Insert: {
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          company_name?: string | null;
          company_website?: string | null;
          contact_email?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          country?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          email_verified?: boolean | null;
          id: string;
          marketing_opt_in?: boolean;
          onboarding_notes?: string | null;
          postal_code?: string | null;
          region?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Update: {
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          company_name?: string | null;
          company_website?: string | null;
          contact_email?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          country?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          email_verified?: boolean | null;
          id?: string;
          marketing_opt_in?: boolean;
          onboarding_notes?: string | null;
          postal_code?: string | null;
          region?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          stripe_customer_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      profile_sensitive: {
        Row: {
          address_enc: string | null;
          contact_email_enc: string | null;
          contact_phone_enc: string | null;
          onboarding_notes_enc: string | null;
          profile_id: string;
          updated_at: string;
        };
        Insert: {
          address_enc?: string | null;
          contact_email_enc?: string | null;
          contact_phone_enc?: string | null;
          onboarding_notes_enc?: string | null;
          profile_id: string;
          updated_at?: string;
        };
        Update: {
          address_enc?: string | null;
          contact_email_enc?: string | null;
          contact_phone_enc?: string | null;
          onboarding_notes_enc?: string | null;
          profile_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profile_sensitive_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "profile_sensitive_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limit_violations: {
        Row: {
          created_at: string | null;
          email: string | null;
          endpoint: string;
          id: string;
          ip_address: unknown;
          limit_threshold: number;
          request_count: number;
          user_agent: string | null;
          violation_type: string;
        };
        Insert: {
          created_at?: string | null;
          email?: string | null;
          endpoint: string;
          id?: string;
          ip_address?: unknown;
          limit_threshold: number;
          request_count: number;
          user_agent?: string | null;
          violation_type: string;
        };
        Update: {
          created_at?: string | null;
          email?: string | null;
          endpoint?: string;
          id?: string;
          ip_address?: unknown;
          limit_threshold?: number;
          request_count?: number;
          user_agent?: string | null;
          violation_type?: string;
        };
        Relationships: [];
      };
      refund: {
        Row: {
          amount: number;
          charge_id: string;
          created_at: string;
          currency: string;
          description: string | null;
          failure_balance_transaction: string | null;
          failure_reason: string | null;
          id: string;
          metadata: Json | null;
          payment_intent_id: string | null;
          profile_id: string;
          reason: string | null;
          receipt_number: string | null;
          status: string;
          stripe_refund_id: string;
          updated_at: string;
        };
        Insert: {
          amount: number;
          charge_id: string;
          created_at?: string;
          currency?: string;
          description?: string | null;
          failure_balance_transaction?: string | null;
          failure_reason?: string | null;
          id?: string;
          metadata?: Json | null;
          payment_intent_id?: string | null;
          profile_id: string;
          reason?: string | null;
          receipt_number?: string | null;
          status: string;
          stripe_refund_id: string;
          updated_at?: string;
        };
        Update: {
          amount?: number;
          charge_id?: string;
          created_at?: string;
          currency?: string;
          description?: string | null;
          failure_balance_transaction?: string | null;
          failure_reason?: string | null;
          id?: string;
          metadata?: Json | null;
          payment_intent_id?: string | null;
          profile_id?: string;
          reason?: string | null;
          receipt_number?: string | null;
          status?: string;
          stripe_refund_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "refund_charge_id_fkey";
            columns: ["charge_id"];
            isOneToOne: false;
            referencedRelation: "charge";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refund_payment_intent_id_fkey";
            columns: ["payment_intent_id"];
            isOneToOne: false;
            referencedRelation: "payment_intent";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refund_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "refund_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      site_analytics: {
        Row: {
          client_site_id: string;
          conversions: number;
          created_at: string;
          id: number;
          metadata: Json;
          metric_date: string;
          page_views: number;
          unique_visitors: number;
          updated_at: string;
        };
        Insert: {
          client_site_id: string;
          conversions?: number;
          created_at?: string;
          id?: number;
          metadata?: Json;
          metric_date: string;
          page_views?: number;
          unique_visitors?: number;
          updated_at?: string;
        };
        Update: {
          client_site_id?: string;
          conversions?: number;
          created_at?: string;
          id?: number;
          metadata?: Json;
          metric_date?: string;
          page_views?: number;
          unique_visitors?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "site_analytics_site_fk";
            columns: ["client_site_id"];
            isOneToOne: false;
            referencedRelation: "client_site";
            referencedColumns: ["id"];
          },
        ];
      };
      site_analytics_events: {
        Row: {
          client_site_id: string;
          event_type: string;
          id: string;
          metadata: Json;
          occurred_at: string;
          session_id: string | null;
          visitor_id: string | null;
        };
        Insert: {
          client_site_id: string;
          event_type: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          session_id?: string | null;
          visitor_id?: string | null;
        };
        Update: {
          client_site_id?: string;
          event_type?: string;
          id?: string;
          metadata?: Json;
          occurred_at?: string;
          session_id?: string | null;
          visitor_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "site_analytics_events_client_site_id_fkey";
            columns: ["client_site_id"];
            isOneToOne: false;
            referencedRelation: "client_site";
            referencedColumns: ["id"];
          },
        ];
      };
      sla_policy: {
        Row: {
          business_hours_only: boolean;
          created_at: string;
          first_response_hours: number;
          id: string;
          priority: Database["public"]["Enums"]["ticket_priority"];
          resolution_hours: number;
          updated_at: string;
        };
        Insert: {
          business_hours_only?: boolean;
          created_at?: string;
          first_response_hours: number;
          id?: string;
          priority: Database["public"]["Enums"]["ticket_priority"];
          resolution_hours: number;
          updated_at?: string;
        };
        Update: {
          business_hours_only?: boolean;
          created_at?: string;
          first_response_hours?: number;
          id?: string;
          priority?: Database["public"]["Enums"]["ticket_priority"];
          resolution_hours?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription: {
        Row: {
          billing_reason: string | null;
          cancel_at: string | null;
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          created_at: string;
          current_period_end: string | null;
          current_period_start: string | null;
          deleted_at: string | null;
          id: string;
          metadata: Json;
          plan_id: string;
          profile_id: string;
          renewal_behavior: string | null;
          status: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id: string | null;
          trial_end: string | null;
          trial_start: string | null;
          updated_at: string;
        };
        Insert: {
          billing_reason?: string | null;
          cancel_at?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          current_period_end?: string | null;
          current_period_start?: string | null;
          deleted_at?: string | null;
          id?: string;
          metadata?: Json;
          plan_id: string;
          profile_id: string;
          renewal_behavior?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          trial_end?: string | null;
          trial_start?: string | null;
          updated_at?: string;
        };
        Update: {
          billing_reason?: string | null;
          cancel_at?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          created_at?: string;
          current_period_end?: string | null;
          current_period_start?: string | null;
          deleted_at?: string | null;
          id?: string;
          metadata?: Json;
          plan_id?: string;
          profile_id?: string;
          renewal_behavior?: string | null;
          status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          trial_end?: string | null;
          trial_start?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscription_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "analytics_mrr";
            referencedColumns: ["plan_id"];
          },
          {
            foreignKeyName: "subscription_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plan";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_plan_fk";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plan_pricing";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      subscription_history: {
        Row: {
          arr_change: number | null;
          changed_by: string | null;
          event_type: string;
          from_plan_id: string | null;
          from_status: string | null;
          id: string;
          metadata: Json | null;
          mrr_change: number | null;
          occurred_at: string;
          profile_id: string;
          prorated_amount: number | null;
          reason: string | null;
          subscription_id: string;
          to_plan_id: string | null;
          to_status: string | null;
        };
        Insert: {
          arr_change?: number | null;
          changed_by?: string | null;
          event_type: string;
          from_plan_id?: string | null;
          from_status?: string | null;
          id?: string;
          metadata?: Json | null;
          mrr_change?: number | null;
          occurred_at?: string;
          profile_id: string;
          prorated_amount?: number | null;
          reason?: string | null;
          subscription_id: string;
          to_plan_id?: string | null;
          to_status?: string | null;
        };
        Update: {
          arr_change?: number | null;
          changed_by?: string | null;
          event_type?: string;
          from_plan_id?: string | null;
          from_status?: string | null;
          id?: string;
          metadata?: Json | null;
          mrr_change?: number | null;
          occurred_at?: string;
          profile_id?: string;
          prorated_amount?: number | null;
          reason?: string | null;
          subscription_id?: string;
          to_plan_id?: string | null;
          to_status?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "subscription_history_from_plan_id_fkey";
            columns: ["from_plan_id"];
            isOneToOne: false;
            referencedRelation: "analytics_mrr";
            referencedColumns: ["plan_id"];
          },
          {
            foreignKeyName: "subscription_history_from_plan_id_fkey";
            columns: ["from_plan_id"];
            isOneToOne: false;
            referencedRelation: "plan";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_from_plan_id_fkey";
            columns: ["from_plan_id"];
            isOneToOne: false;
            referencedRelation: "plan_pricing";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_subscription_id_fkey";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_to_plan_id_fkey";
            columns: ["to_plan_id"];
            isOneToOne: false;
            referencedRelation: "analytics_mrr";
            referencedColumns: ["plan_id"];
          },
          {
            foreignKeyName: "subscription_history_to_plan_id_fkey";
            columns: ["to_plan_id"];
            isOneToOne: false;
            referencedRelation: "plan";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscription_history_to_plan_id_fkey";
            columns: ["to_plan_id"];
            isOneToOne: false;
            referencedRelation: "plan_pricing";
            referencedColumns: ["id"];
          },
        ];
      };
      support_ticket: {
        Row: {
          assigned_to_profile_id: string | null;
          category: Database["public"]["Enums"]["ticket_category"];
          client_site_id: string | null;
          closed_at: string | null;
          created_at: string;
          created_by_profile_id: string;
          id: string;
          last_reply_at: string | null;
          message: string;
          metadata: Json;
          priority: Database["public"]["Enums"]["ticket_priority"];
          profile_id: string;
          resolved_at: string | null;
          status: Database["public"]["Enums"]["ticket_status"];
          subject: string;
          subscription_id: string | null;
          updated_at: string;
        };
        Insert: {
          assigned_to_profile_id?: string | null;
          category?: Database["public"]["Enums"]["ticket_category"];
          client_site_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          created_by_profile_id: string;
          id?: string;
          last_reply_at?: string | null;
          message: string;
          metadata?: Json;
          priority?: Database["public"]["Enums"]["ticket_priority"];
          profile_id: string;
          resolved_at?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          subject: string;
          subscription_id?: string | null;
          updated_at?: string;
        };
        Update: {
          assigned_to_profile_id?: string | null;
          category?: Database["public"]["Enums"]["ticket_category"];
          client_site_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          created_by_profile_id?: string;
          id?: string;
          last_reply_at?: string | null;
          message?: string;
          metadata?: Json;
          priority?: Database["public"]["Enums"]["ticket_priority"];
          profile_id?: string;
          resolved_at?: string | null;
          status?: Database["public"]["Enums"]["ticket_status"];
          subject?: string;
          subscription_id?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "support_ticket_assignee_fk";
            columns: ["assigned_to_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_assignee_fk";
            columns: ["assigned_to_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_creator_fk";
            columns: ["created_by_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_creator_fk";
            columns: ["created_by_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_profile_fk";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_site_fk";
            columns: ["client_site_id"];
            isOneToOne: false;
            referencedRelation: "client_site";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "support_ticket_subscription_fk";
            columns: ["subscription_id"];
            isOneToOne: false;
            referencedRelation: "subscription";
            referencedColumns: ["id"];
          },
        ];
      };
      ticket_reply: {
        Row: {
          author_profile_id: string;
          created_at: string;
          id: string;
          is_internal: boolean;
          message: string;
          support_ticket_id: string;
          updated_at: string;
        };
        Insert: {
          author_profile_id: string;
          created_at?: string;
          id?: string;
          is_internal?: boolean;
          message: string;
          support_ticket_id: string;
          updated_at?: string;
        };
        Update: {
          author_profile_id?: string;
          created_at?: string;
          id?: string;
          is_internal?: boolean;
          message?: string;
          support_ticket_id?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ticket_reply_author_fk";
            columns: ["author_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ticket_reply_author_fk";
            columns: ["author_profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ticket_reply_ticket_fk";
            columns: ["support_ticket_id"];
            isOneToOne: false;
            referencedRelation: "support_ticket";
            referencedColumns: ["id"];
          },
        ];
      };
      user_activity_log: {
        Row: {
          action: string;
          created_at: string;
          id: string;
          ip_address: unknown;
          profile_id: string | null;
          route: string | null;
          status: string | null;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          created_at?: string;
          id?: string;
          ip_address?: unknown;
          profile_id?: string | null;
          route?: string | null;
          status?: string | null;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          created_at?: string;
          id?: string;
          ip_address?: unknown;
          profile_id?: string | null;
          route?: string | null;
          status?: string | null;
          user_agent?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "user_activity_log_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_activity_log_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      user_preferences: {
        Row: {
          appearance: string;
          created_at: string;
          email_notifications: boolean;
          language: string;
          marketing_opt_in: boolean;
          profile_id: string;
          sms_notifications: boolean;
          timezone: string;
          updated_at: string;
        };
        Insert: {
          appearance?: string;
          created_at?: string;
          email_notifications?: boolean;
          language?: string;
          marketing_opt_in?: boolean;
          profile_id: string;
          sms_notifications?: boolean;
          timezone?: string;
          updated_at?: string;
        };
        Update: {
          appearance?: string;
          created_at?: string;
          email_notifications?: boolean;
          language?: string;
          marketing_opt_in?: boolean;
          profile_id?: string;
          sms_notifications?: boolean;
          timezone?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_preferences_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_preferences_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      verification_reminders: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          last_sent_at: string;
          profile_id: string;
          reminder_count: number;
        };
        Insert: {
          created_at?: string;
          email: string;
          id?: string;
          last_sent_at?: string;
          profile_id: string;
          reminder_count?: number;
        };
        Update: {
          created_at?: string;
          email?: string;
          id?: string;
          last_sent_at?: string;
          profile_id?: string;
          reminder_count?: number;
        };
        Relationships: [
          {
            foreignKeyName: "verification_reminders_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "verification_reminders_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: true;
            referencedRelation: "profile_redacted";
            referencedColumns: ["id"];
          },
        ];
      };
      webhook_events: {
        Row: {
          created_at: string | null;
          error_message: string | null;
          event_data: Json | null;
          event_type: string;
          id: string;
          last_retry_at: string | null;
          processed_at: string | null;
          retry_count: number | null;
          status: string | null;
          stripe_event_id: string;
          updated_at: string | null;
        };
        Insert: {
          created_at?: string | null;
          error_message?: string | null;
          event_data?: Json | null;
          event_type: string;
          id?: string;
          last_retry_at?: string | null;
          processed_at?: string | null;
          retry_count?: number | null;
          status?: string | null;
          stripe_event_id: string;
          updated_at?: string | null;
        };
        Update: {
          created_at?: string | null;
          error_message?: string | null;
          event_data?: Json | null;
          event_type?: string;
          id?: string;
          last_retry_at?: string | null;
          processed_at?: string | null;
          retry_count?: number | null;
          status?: string | null;
          stripe_event_id?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      analytics_mrr: {
        Row: {
          arr_cad: number | null;
          customers: number | null;
          month: string | null;
          mrr_cad: number | null;
          normalized_mrr_cad: number | null;
          plan_id: string | null;
          plan_name: string | null;
        };
        Relationships: [];
      };
      plan_pricing: {
        Row: {
          created_at: string | null;
          currency_code: string | null;
          description: string | null;
          features: Json | null;
          id: string | null;
          is_active: boolean | null;
          name: string | null;
          page_limit: number | null;
          price_monthly_cents: number | null;
          price_yearly_cents: number | null;
          revision_limit: number | null;
          setup_fee_cents: number | null;
          slug: string | null;
          sort_order: number | null;
          stripe_price_id_monthly: string | null;
          stripe_price_id_yearly: string | null;
          stripe_product_id: string | null;
          updated_at: string | null;
          yearly_monthly_rate_cents: number | null;
          yearly_savings_cents: number | null;
          yearly_savings_percent: number | null;
        };
        Insert: {
          created_at?: string | null;
          currency_code?: string | null;
          description?: string | null;
          features?: Json | null;
          id?: string | null;
          is_active?: boolean | null;
          name?: string | null;
          page_limit?: number | null;
          price_monthly_cents?: number | null;
          price_yearly_cents?: number | null;
          revision_limit?: number | null;
          setup_fee_cents?: number | null;
          slug?: string | null;
          sort_order?: number | null;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_yearly?: string | null;
          stripe_product_id?: string | null;
          updated_at?: string | null;
          yearly_monthly_rate_cents?: never;
          yearly_savings_cents?: never;
          yearly_savings_percent?: never;
        };
        Update: {
          created_at?: string | null;
          currency_code?: string | null;
          description?: string | null;
          features?: Json | null;
          id?: string | null;
          is_active?: boolean | null;
          name?: string | null;
          page_limit?: number | null;
          price_monthly_cents?: number | null;
          price_yearly_cents?: number | null;
          revision_limit?: number | null;
          setup_fee_cents?: number | null;
          slug?: string | null;
          sort_order?: number | null;
          stripe_price_id_monthly?: string | null;
          stripe_price_id_yearly?: string | null;
          stripe_product_id?: string | null;
          updated_at?: string | null;
          yearly_monthly_rate_cents?: never;
          yearly_savings_cents?: never;
          yearly_savings_percent?: never;
        };
        Relationships: [];
      };
      profile_redacted: {
        Row: {
          address_json: string | null;
          company_name: string | null;
          company_website: string | null;
          contact_email: string | null;
          contact_name: string | null;
          contact_phone: string | null;
          created_at: string | null;
          deleted_at: string | null;
          id: string | null;
          marketing_opt_in: boolean | null;
          onboarding_notes: string | null;
          role: Database["public"]["Enums"]["user_role"] | null;
          updated_at: string | null;
        };
        Relationships: [];
      };
      vw_database_health: {
        Row: {
          category: string | null;
          value: string | null;
        };
        Relationships: [];
      };
      vw_foreign_keys: {
        Row: {
          delete_rule: string | null;
          from_column: unknown;
          from_table: unknown;
          table_schema: unknown;
          to_column: unknown;
          to_table: unknown;
          update_rule: string | null;
        };
        Relationships: [];
      };
      vw_index_usage: {
        Row: {
          index_size: string | null;
          indexname: unknown;
          scans: number | null;
          schemaname: unknown;
          tablename: unknown;
          tuples_fetched: number | null;
          tuples_read: number | null;
          usage_category: string | null;
        };
        Relationships: [];
      };
      vw_rls_coverage: {
        Row: {
          policies: unknown[] | null;
          policy_count: number | null;
          rls_enabled: boolean | null;
          status: string | null;
          tablename: unknown;
        };
        Relationships: [];
      };
      vw_table_stats: {
        Row: {
          dead_row_percent: number | null;
          dead_rows: number | null;
          indexes_size: string | null;
          last_analyze: string | null;
          last_autoanalyze: string | null;
          last_autovacuum: string | null;
          last_vacuum: string | null;
          live_rows: number | null;
          schemaname: unknown;
          table_size: string | null;
          tablename: unknown;
          total_size: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      analyze_churn_patterns: {
        Args: { p_months?: number };
        Returns: {
          avg_lifetime_days: number;
          avg_lifetime_revenue: number;
          churn_after_trial: number;
          churn_within_trial: number;
          churned_count: number;
          most_common_duration_range: string;
          plan_name: string;
        }[];
      };
      archive_audit_logs: { Args: never; Returns: undefined };
      calculate_churn_rate: {
        Args: { p_end_date?: string; p_start_date?: string };
        Returns: {
          active_end: number;
          active_start: number;
          churn_rate: number;
          churned: number;
          gross_churn_rate: number;
          net_churn_rate: number;
          new_subscriptions: number;
          period: string;
          retention_rate: number;
        }[];
      };
      calculate_cohort_retention: {
        Args: { p_cohort_end?: string; p_cohort_start?: string };
        Returns: {
          churned_customers: number;
          cohort_month: string;
          cohort_size: number;
          months_since_start: number;
          retained_customers: number;
          retention_percentage: number;
        }[];
      };
      calculate_current_mrr: {
        Args: never;
        Returns: {
          active_customers: number;
          average_revenue_per_user: number;
          total_arr: number;
          total_mrr: number;
        }[];
      };
      calculate_customer_ltv: {
        Args: never;
        Returns: {
          avg_monthly_value: number;
          current_plan: string;
          customer_email: string;
          customer_name: string;
          first_subscription_date: string;
          is_active: boolean;
          last_cancellation_date: string;
          profile_id: string;
          subscription_count: number;
          total_ltv: number;
          total_months_subscribed: number;
        }[];
      };
      calculate_customer_segments: {
        Args: never;
        Returns: {
          avg_ltv: number;
          customer_count: number;
          percentage: number;
          segment: string;
          total_mrr: number;
        }[];
      };
      calculate_ltv_by_plan: {
        Args: never;
        Returns: {
          avg_ltv: number;
          avg_subscription_length_months: number;
          customer_count: number;
          median_ltv: number;
          plan_id: string;
          plan_name: string;
          total_ltv: number;
        }[];
      };
      calculate_mrr_growth: {
        Args: { p_months?: number };
        Returns: {
          churned_mrr: number;
          customers: number;
          mom_growth_percentage: number;
          month: string;
          mrr: number;
          new_mrr: number;
        }[];
      };
      calculate_revenue_by_plan: {
        Args: never;
        Returns: {
          active_count: number;
          monthly_price: number;
          monthly_revenue: number;
          percentage: number;
          plan_id: string;
          plan_name: string;
          yearly_revenue: number;
        }[];
      };
      check_login_rate_limit: {
        Args: { p_email: string; p_ip: unknown };
        Returns: Json;
      };
      check_sla_status: {
        Args: { p_ticket_id: string };
        Returns: {
          created_at: string;
          first_response_breached: boolean;
          first_response_hours: number;
          first_response_target_hours: number;
          last_reply_at: string;
          priority: Database["public"]["Enums"]["ticket_priority"];
          resolution_breached: boolean;
          resolution_hours: number;
          resolution_target_hours: number;
          resolved_at: string;
          sla_status: string;
          ticket_id: string;
          time_to_first_response_breach_hours: number;
          time_to_resolution_breach_hours: number;
        }[];
      };
      check_webhook_event_processed: {
        Args: { p_stripe_event_id: string };
        Returns: boolean;
      };
      cleanup_expired_notifications: { Args: never; Returns: undefined };
      cleanup_expired_otp_codes: { Args: never; Returns: undefined };
      complete_webhook_event: {
        Args: { p_stripe_event_id: string };
        Returns: undefined;
      };
      fail_webhook_event: {
        Args: { p_error_message: string; p_stripe_event_id: string };
        Returns: undefined;
      };
      generate_otp_code: { Args: { length?: number }; Returns: string };
      get_rate_limit_stats: { Args: { p_hours_ago?: number }; Returns: Json };
      get_sla_compliance_metrics: {
        Args: { end_date?: string; start_date?: string };
        Returns: {
          avg_first_response_hours: number;
          avg_resolution_hours: number;
          by_priority: Json;
          compliance_rate: number;
          median_first_response_hours: number;
          median_resolution_hours: number;
          tickets_breached_sla: number;
          tickets_met_sla: number;
          total_tickets: number;
        }[];
      };
      get_tickets_at_risk: {
        Args: never;
        Returns: {
          assigned_to_profile_id: string;
          created_at: string;
          hours_remaining: number;
          hours_since_creation: number;
          priority: Database["public"]["Enums"]["ticket_priority"];
          sla_status: string;
          status: Database["public"]["Enums"]["ticket_status"];
          subject: string;
          target_resolution_hours: number;
          ticket_id: string;
        }[];
      };
      get_unverified_users_for_reminders: {
        Args: never;
        Returns: {
          created_at: string;
          email: string;
          profile_id: string;
          reminder_count: number;
        }[];
      };
      identify_high_value_customers: {
        Args: { p_min_ltv?: number };
        Returns: {
          current_plan: string;
          customer_email: string;
          customer_name: string;
          is_active: boolean;
          months_subscribed: number;
          profile_id: string;
          risk_level: string;
          total_ltv: number;
        }[];
      };
      log_otp_attempt: {
        Args: {
          p_email: string;
          p_success: boolean;
          p_verification_type: string;
        };
        Returns: undefined;
      };
      log_rate_limit_violation: {
        Args: {
          p_email: string;
          p_endpoint: string;
          p_ip_address: unknown;
          p_limit_threshold: number;
          p_request_count: number;
          p_user_agent?: string;
          p_violation_type: string;
        };
        Returns: Json;
      };
      record_verification_reminder_sent: {
        Args: { p_email: string; p_profile_id: string };
        Returns: undefined;
      };
      record_webhook_event: {
        Args: {
          p_event_data: Json;
          p_event_type: string;
          p_stripe_event_id: string;
        };
        Returns: string;
      };
      refresh_analytics_mrr: { Args: never; Returns: undefined };
      rollup_site_analytics: {
        Args: { p_target_date?: string };
        Returns: undefined;
      };
      search_profiles: {
        Args: { limit_count?: number; search_term: string };
        Returns: {
          company_name: string;
          contact_email: string;
          contact_name: string;
          id: string;
          role: Database["public"]["Enums"]["user_role"];
          similarity: number;
        }[];
      };
      search_sites: {
        Args: { limit_count?: number; search_term: string };
        Returns: {
          custom_domain: string;
          deployment_url: string;
          id: string;
          profile_id: string;
          similarity: number;
          site_name: string;
          status: Database["public"]["Enums"]["site_status"];
        }[];
      };
      search_tickets: {
        Args: { limit_count?: number; search_term: string };
        Returns: {
          id: string;
          message: string;
          priority: Database["public"]["Enums"]["ticket_priority"];
          profile_id: string;
          similarity: number;
          status: Database["public"]["Enums"]["ticket_status"];
          subject: string;
        }[];
      };
      show_limit: { Args: never; Returns: number };
      show_trgm: { Args: { "": string }; Returns: string[] };
      sync_stripe_prices: {
        Args: {
          p_monthly_price: number;
          p_product_id: string;
          p_yearly_price: number;
        };
        Returns: undefined;
      };
      unlock_account: {
        Args: { p_admin_id: string; p_email: string };
        Returns: Json;
      };
      verify_otp: {
        Args: {
          p_email: string;
          p_otp_code: string;
          p_verification_type: string;
        };
        Returns: Json;
      };
    };
    Enums: {
      notification_type:
        | "subscription"
        | "billing"
        | "support"
        | "site_status"
        | "system"
        | "onboarding";
      site_status:
        | "pending"
        | "in_production"
        | "awaiting_client_content"
        | "ready_for_review"
        | "live"
        | "paused"
        | "archived";
      subscription_status:
        | "trialing"
        | "active"
        | "past_due"
        | "canceled"
        | "incomplete"
        | "unpaid";
      ticket_category:
        | "technical"
        | "content_change"
        | "general_inquiry"
        | "billing";
      ticket_priority: "low" | "medium" | "high" | "urgent";
      ticket_status:
        | "open"
        | "in_progress"
        | "awaiting_client"
        | "resolved"
        | "closed";
      user_role: "admin" | "client";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      notification_type: [
        "subscription",
        "billing",
        "support",
        "site_status",
        "system",
        "onboarding",
      ],
      site_status: [
        "pending",
        "in_production",
        "awaiting_client_content",
        "ready_for_review",
        "live",
        "paused",
        "archived",
      ],
      subscription_status: [
        "trialing",
        "active",
        "past_due",
        "canceled",
        "incomplete",
        "unpaid",
      ],
      ticket_category: [
        "technical",
        "content_change",
        "general_inquiry",
        "billing",
      ],
      ticket_priority: ["low", "medium", "high", "urgent"],
      ticket_status: [
        "open",
        "in_progress",
        "awaiting_client",
        "resolved",
        "closed",
      ],
      user_role: ["admin", "client"],
    },
  },
} as const;
